name: mkdocs
channels:
  - conda-forge
  - defaults
dependencies:
  - mkdocs
  - mkdocs-git-committers-plugin-2
  - mkdocs-git-revision-date-localized-plugin
  - mkdocs-material
  - pymdown-extensions
