helmDefaults:
  kubeContext: staerkcloud
repositories:
  - name: authentik
    url: https://charts.goauthentik.io

  - name: bitnami
    url: https://charts.bitnami.com/bitnami

  - name: cloudflare
    url: https://cloudflare.github.io/helm-charts

  - name: longhorn
    url: https://charts.longhorn.io

  - name: mattermost
    url: https://helm.mattermost.com

  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx

  - name: jetstack
    url: https://charts.jetstack.io

  - name: traefik
    url: https://traefik.github.io/charts

releases:
  - name: longhorn
    namespace: longhorn-system
    createNamespace: true
    chart: longhorn/longhorn
    hooks:
      - events: ["prepare"]
        showlogs: true
        command: "kubectl"
        args:
          - "apply"
          - "-f"
          - "https://raw.githubusercontent.com/longhorn/longhorn/master/deploy/prerequisite/longhorn-iscsi-installation.yaml"
      - events: ["prepare"]
        showlogs: true
        command: "kubectl"
        args:
          - "apply"
          - "-f"
          - "https://raw.githubusercontent.com/longhorn/longhorn/master/deploy/prerequisite/longhorn-nfs-installation.yaml"

  - name: metallb
    namespace: metallb-system
    createNamespace: true
    chart: bitnami/metallb
    hooks:
      - events: ["postsync"]
        showlogs: true
        command: "kustomize"
        args:
          - "build"
          - "./metallb"
          - "--output"
          - "./metallb/output.yaml"
      - events: ["postsync"]
        showlogs: true
        command: "kubectl"
        args:
          - "apply"
          - "-f"
          - "./metallb/output.yaml"
    values:
      - metallb/values.yaml

  - name: traefik
    namespace: traefik-system
    createNamespace: true
    chart: traefik/traefik
    hooks:
      - events: ["postsync"]
        showlogs: true
        command: "kustomize"
        args:
          - "build"
          - "./traefik"
          - "--output"
          - "./traefik/output.yaml"
      - events: ["postsync"]
        showlogs: true
        command: "kubectl"
        args:
          - "kubectl"
          - "apply"
          - "-f"
          - "./traefik/output.yaml"
    values:
      - traefik/values.yaml

  - name: nginx
    namespace: nginx-system
    createNamespace: true
    chart: ingress-nginx/ingress-nginx
    values:
      - nginx/values.yaml

  - name: cert-manager
    namespace: cert-manager
    createNamespace: true
    chart: jetstack/cert-manager
    values:
      - cert-manager/values.yaml

  - name: cloudflared
    namespace: cloudflare-tunnel
    createNamespace: true
    chart: cloudflare/cloudflare-tunnel-remote
    values:
      - cloudflared/values.yaml

  - name: authentik
    namespace: authentik
    createNamespace: true
    chart: authentik/authentik
    values:
      - authentik/values.yaml
