apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami-deployment
  namespace: hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whoami-pod
  template:
    metadata:
      labels:
        app: whoami-pod
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: whoami
          image: registry.valhal.cloud/hello-world/whoami:latest
          ports:
            - name: http
              containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: whoami-serivce
  namespace: hello-world
spec:
  selector:
    app: whoami
  ports:
    - name: web
      port: 80
      targetPort: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: whoami-ingress
  namespace: hello-world
spec:
  rules:
    - host: whoami.valhal.dev
      http:
        paths:
          - pathType: ImplementationSpecific
            path: "/"
            backend:
              service:
                name: whoami-serivce
                port:
                  name: web
